/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalPatientsToday' : bigint,
  'avgWaitTime' : bigint,
  'perDoctorStats' : Array<
    [bigint, { 'totalPatients' : bigint, 'avgWaitTime' : bigint }]
  >,
}
export type ConsultationStatus = { 'serving' : null } |
  { 'cancelled' : null } |
  { 'skipped' : null } |
  { 'completed' : null } |
  { 'called' : null } |
  { 'waiting' : null };
export interface ConsultationToken {
  'id' : bigint,
  'status' : ConsultationStatus,
  'doctorId' : bigint,
  'tokenNumber' : string,
  'createdAt' : bigint,
  'isFamilyMember' : boolean,
  'queuePosition' : bigint,
  'calledAt' : [] | [bigint],
  'patientPrincipal' : Principal,
  'memberName' : [] | [string],
  'patientName' : string,
}
export interface Doctor {
  'id' : bigint,
  'principal' : [] | [Principal],
  'avgConsultationMinutes' : bigint,
  'isPaused' : boolean,
  'name' : string,
  'isActive' : boolean,
  'specialty' : string,
}
export interface DoctorRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'specialty' : string,
  'doctorName' : string,
  'requestedBy' : Principal,
}
export type TokenResponse = { 'more_time' : null } |
  { 'cancel' : null } |
  { 'coming' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDoctor' : ActorMethod<[string, string, bigint, Principal], undefined>,
  'addEmergencyPatient' : ActorMethod<[bigint, string], bigint>,
  'approveDoctorRequest' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateETA' : ActorMethod<[bigint], [] | [bigint]>,
  'callNextPatient' : ActorMethod<[bigint], [] | [bigint]>,
  'cancelToken' : ActorMethod<[bigint], undefined>,
  'completeToken' : ActorMethod<[bigint], undefined>,
  'generateToken' : ActorMethod<
    [bigint, string, boolean, [] | [string]],
    bigint
  >,
  'getAllQueues' : ActorMethod<[], Array<[bigint, Array<ConsultationToken>]>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctor' : ActorMethod<[bigint], [] | [Doctor]>,
  'getDoctorRequests' : ActorMethod<[], Array<DoctorRequest>>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'getMyTokens' : ActorMethod<[], Array<ConsultationToken>>,
  'getQueue' : ActorMethod<[bigint], Array<ConsultationToken>>,
  'getTokenHistory' : ActorMethod<[], Array<ConsultationToken>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTokenSkipped' : ActorMethod<[bigint], undefined>,
  'pauseQueue' : ActorMethod<[bigint], undefined>,
  'rejectDoctorRequest' : ActorMethod<[bigint], undefined>,
  'requestDoctor' : ActorMethod<[string, string], undefined>,
  'resetDailyQueues' : ActorMethod<[], undefined>,
  'respondToCall' : ActorMethod<[bigint, TokenResponse], undefined>,
  'resumeQueue' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];