/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConsultationStatus = IDL.Variant({
  'serving' : IDL.Null,
  'cancelled' : IDL.Null,
  'skipped' : IDL.Null,
  'completed' : IDL.Null,
  'called' : IDL.Null,
  'waiting' : IDL.Null,
});
export const ConsultationToken = IDL.Record({
  'id' : IDL.Nat,
  'status' : ConsultationStatus,
  'doctorId' : IDL.Nat,
  'tokenNumber' : IDL.Text,
  'createdAt' : IDL.Int,
  'isFamilyMember' : IDL.Bool,
  'queuePosition' : IDL.Nat,
  'calledAt' : IDL.Opt(IDL.Int),
  'patientPrincipal' : IDL.Principal,
  'memberName' : IDL.Opt(IDL.Text),
  'patientName' : IDL.Text,
});
export const Analytics = IDL.Record({
  'totalPatientsToday' : IDL.Nat,
  'avgWaitTime' : IDL.Nat,
  'perDoctorStats' : IDL.Vec(
    IDL.Tuple(
      IDL.Nat,
      IDL.Record({ 'totalPatients' : IDL.Nat, 'avgWaitTime' : IDL.Nat }),
    )
  ),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Opt(IDL.Principal),
  'avgConsultationMinutes' : IDL.Nat,
  'isPaused' : IDL.Bool,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'specialty' : IDL.Text,
});
export const DoctorRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'specialty' : IDL.Text,
  'doctorName' : IDL.Text,
  'requestedBy' : IDL.Principal,
});
export const TokenResponse = IDL.Variant({
  'more_time' : IDL.Null,
  'cancel' : IDL.Null,
  'coming' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Principal], [], []),
  'addEmergencyPatient' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'approveDoctorRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateETA' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'callNextPatient' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
  'cancelToken' : IDL.Func([IDL.Nat], [], []),
  'completeToken' : IDL.Func([IDL.Nat], [], []),
  'generateToken' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getAllQueues' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(ConsultationToken)))],
      ['query'],
    ),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctor' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
  'getDoctorRequests' : IDL.Func([], [IDL.Vec(DoctorRequest)], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getMyTokens' : IDL.Func([], [IDL.Vec(ConsultationToken)], ['query']),
  'getQueue' : IDL.Func([IDL.Nat], [IDL.Vec(ConsultationToken)], ['query']),
  'getTokenHistory' : IDL.Func([], [IDL.Vec(ConsultationToken)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTokenSkipped' : IDL.Func([IDL.Nat], [], []),
  'pauseQueue' : IDL.Func([IDL.Nat], [], []),
  'rejectDoctorRequest' : IDL.Func([IDL.Nat], [], []),
  'requestDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetDailyQueues' : IDL.Func([], [], []),
  'respondToCall' : IDL.Func([IDL.Nat, TokenResponse], [], []),
  'resumeQueue' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConsultationStatus = IDL.Variant({
    'serving' : IDL.Null,
    'cancelled' : IDL.Null,
    'skipped' : IDL.Null,
    'completed' : IDL.Null,
    'called' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const ConsultationToken = IDL.Record({
    'id' : IDL.Nat,
    'status' : ConsultationStatus,
    'doctorId' : IDL.Nat,
    'tokenNumber' : IDL.Text,
    'createdAt' : IDL.Int,
    'isFamilyMember' : IDL.Bool,
    'queuePosition' : IDL.Nat,
    'calledAt' : IDL.Opt(IDL.Int),
    'patientPrincipal' : IDL.Principal,
    'memberName' : IDL.Opt(IDL.Text),
    'patientName' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'totalPatientsToday' : IDL.Nat,
    'avgWaitTime' : IDL.Nat,
    'perDoctorStats' : IDL.Vec(
      IDL.Tuple(
        IDL.Nat,
        IDL.Record({ 'totalPatients' : IDL.Nat, 'avgWaitTime' : IDL.Nat }),
      )
    ),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Opt(IDL.Principal),
    'avgConsultationMinutes' : IDL.Nat,
    'isPaused' : IDL.Bool,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'specialty' : IDL.Text,
  });
  const DoctorRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'specialty' : IDL.Text,
    'doctorName' : IDL.Text,
    'requestedBy' : IDL.Principal,
  });
  const TokenResponse = IDL.Variant({
    'more_time' : IDL.Null,
    'cancel' : IDL.Null,
    'coming' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDoctor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Principal],
        [],
        [],
      ),
    'addEmergencyPatient' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'approveDoctorRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateETA' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'callNextPatient' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
    'cancelToken' : IDL.Func([IDL.Nat], [], []),
    'completeToken' : IDL.Func([IDL.Nat], [], []),
    'generateToken' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getAllQueues' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(ConsultationToken)))],
        ['query'],
      ),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctor' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
    'getDoctorRequests' : IDL.Func([], [IDL.Vec(DoctorRequest)], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getMyTokens' : IDL.Func([], [IDL.Vec(ConsultationToken)], ['query']),
    'getQueue' : IDL.Func([IDL.Nat], [IDL.Vec(ConsultationToken)], ['query']),
    'getTokenHistory' : IDL.Func([], [IDL.Vec(ConsultationToken)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTokenSkipped' : IDL.Func([IDL.Nat], [], []),
    'pauseQueue' : IDL.Func([IDL.Nat], [], []),
    'rejectDoctorRequest' : IDL.Func([IDL.Nat], [], []),
    'requestDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetDailyQueues' : IDL.Func([], [], []),
    'respondToCall' : IDL.Func([IDL.Nat, TokenResponse], [], []),
    'resumeQueue' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };