/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Analytics {
    totalPatientsToday: bigint;
    avgWaitTime: bigint;
    perDoctorStats: Array<[bigint, {
            totalPatients: bigint;
            avgWaitTime: bigint;
        }]>;
}
export interface ConsultationToken {
    id: bigint;
    status: ConsultationStatus;
    doctorId: bigint;
    tokenNumber: string;
    createdAt: bigint;
    isFamilyMember: boolean;
    queuePosition: bigint;
    calledAt?: bigint;
    patientPrincipal: Principal;
    memberName?: string;
    patientName: string;
}
export interface Doctor {
    id: bigint;
    principal?: Principal;
    avgConsultationMinutes: bigint;
    isPaused: boolean;
    name: string;
    isActive: boolean;
    specialty: string;
}
export interface DoctorRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    specialty: string;
    doctorName: string;
    requestedBy: Principal;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum ConsultationStatus {
    serving = "serving",
    cancelled = "cancelled",
    skipped = "skipped",
    completed = "completed",
    called = "called",
    waiting = "waiting"
}
export enum TokenResponse {
    more_time = "more_time",
    cancel = "cancel",
    coming = "coming"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDoctor(name: string, specialty: string, avgConsultationMinutes: bigint, doctorPrincipal: Principal): Promise<void>;
    addEmergencyPatient(doctorId: bigint, patientName: string): Promise<bigint>;
    approveDoctorRequest(requestId: bigint, doctorPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateETA(tokenId: bigint): Promise<bigint | null>;
    callNextPatient(doctorId: bigint): Promise<bigint | null>;
    cancelToken(tokenId: bigint): Promise<void>;
    completeToken(tokenId: bigint): Promise<void>;
    generateToken(doctorId: bigint, patientName: string, isFamilyMember: boolean, memberName: string | null): Promise<bigint>;
    getAllQueues(): Promise<Array<[bigint, Array<ConsultationToken>]>>;
    getAnalytics(): Promise<Analytics>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDoctor(doctorId: bigint): Promise<Doctor | null>;
    getDoctorRequests(): Promise<Array<DoctorRequest>>;
    getDoctors(): Promise<Array<Doctor>>;
    getMyTokens(): Promise<Array<ConsultationToken>>;
    getQueue(doctorId: bigint): Promise<Array<ConsultationToken>>;
    getTokenHistory(): Promise<Array<ConsultationToken>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markTokenSkipped(tokenId: bigint): Promise<void>;
    pauseQueue(doctorId: bigint): Promise<void>;
    rejectDoctorRequest(requestId: bigint): Promise<void>;
    requestDoctor(doctorName: string, specialty: string): Promise<void>;
    resetDailyQueues(): Promise<void>;
    respondToCall(tokenId: bigint, response: TokenResponse): Promise<void>;
    resumeQueue(doctorId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { ConsultationStatus as _ConsultationStatus, ConsultationToken as _ConsultationToken, Doctor as _Doctor, DoctorRequest as _DoctorRequest, TokenResponse as _TokenResponse, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDoctor(arg0: string, arg1: string, arg2: bigint, arg3: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoctor(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoctor(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addEmergencyPatient(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmergencyPatient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmergencyPatient(arg0, arg1);
            return result;
        }
    }
    async approveDoctorRequest(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDoctorRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDoctorRequest(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateETA(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateETA(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateETA(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async callNextPatient(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.callNextPatient(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.callNextPatient(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelToken(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelToken(arg0);
            return result;
        }
    }
    async completeToken(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeToken(arg0);
            return result;
        }
    }
    async generateToken(arg0: bigint, arg1: string, arg2: boolean, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generateToken(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateToken(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getAllQueues(): Promise<Array<[bigint, Array<ConsultationToken>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQueues();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQueues();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctor(arg0: bigint): Promise<Doctor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorRequests(): Promise<Array<DoctorRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorRequests();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorRequests();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctors();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctors();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTokens(): Promise<Array<ConsultationToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTokens();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTokens();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQueue(arg0: bigint): Promise<Array<ConsultationToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueue(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueue(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenHistory(): Promise<Array<ConsultationToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenHistory();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenHistory();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markTokenSkipped(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTokenSkipped(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTokenSkipped(arg0);
            return result;
        }
    }
    async pauseQueue(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseQueue(arg0);
            return result;
        }
    }
    async rejectDoctorRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDoctorRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDoctorRequest(arg0);
            return result;
        }
    }
    async requestDoctor(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestDoctor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestDoctor(arg0, arg1);
            return result;
        }
    }
    async resetDailyQueues(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDailyQueues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDailyQueues();
            return result;
        }
    }
    async respondToCall(arg0: bigint, arg1: TokenResponse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToCall(arg0, to_candid_TokenResponse_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToCall(arg0, to_candid_TokenResponse_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async resumeQueue(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeQueue(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_ConsultationStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationStatus): ConsultationStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ConsultationToken_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationToken): ConsultationToken {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DoctorRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoctorRequest): DoctorRequest {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Doctor_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Doctor): Doctor {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Doctor]): Doctor | null {
    return value.length === 0 ? null : from_candid_Doctor_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: [] | [Principal];
    avgConsultationMinutes: bigint;
    isPaused: boolean;
    name: string;
    isActive: boolean;
    specialty: string;
}): {
    id: bigint;
    principal?: Principal;
    avgConsultationMinutes: bigint;
    isPaused: boolean;
    name: string;
    isActive: boolean;
    specialty: string;
} {
    return {
        id: value.id,
        principal: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.principal)),
        avgConsultationMinutes: value.avgConsultationMinutes,
        isPaused: value.isPaused,
        name: value.name,
        isActive: value.isActive,
        specialty: value.specialty
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    specialty: string;
    doctorName: string;
    requestedBy: Principal;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    specialty: string;
    doctorName: string;
    requestedBy: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n24(_uploadFile, _downloadFile, value.status),
        specialty: value.specialty,
        doctorName: value.doctorName,
        requestedBy: value.requestedBy
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ConsultationStatus;
    doctorId: bigint;
    tokenNumber: string;
    createdAt: bigint;
    isFamilyMember: boolean;
    queuePosition: bigint;
    calledAt: [] | [bigint];
    patientPrincipal: Principal;
    memberName: [] | [string];
    patientName: string;
}): {
    id: bigint;
    status: ConsultationStatus;
    doctorId: bigint;
    tokenNumber: string;
    createdAt: bigint;
    isFamilyMember: boolean;
    queuePosition: bigint;
    calledAt?: bigint;
    patientPrincipal: Principal;
    memberName?: string;
    patientName: string;
} {
    return {
        id: value.id,
        status: from_candid_ConsultationStatus_n10(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        tokenNumber: value.tokenNumber,
        createdAt: value.createdAt,
        isFamilyMember: value.isFamilyMember,
        queuePosition: value.queuePosition,
        calledAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.calledAt)),
        patientPrincipal: value.patientPrincipal,
        memberName: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.memberName)),
        patientName: value.patientName
    };
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, Array<_ConsultationToken>]): [bigint, Array<ConsultationToken>] {
    return [
        value[0],
        from_candid_vec_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serving: null;
} | {
    cancelled: null;
} | {
    skipped: null;
} | {
    completed: null;
} | {
    called: null;
} | {
    waiting: null;
}): ConsultationStatus {
    return "serving" in value ? ConsultationStatus.serving : "cancelled" in value ? ConsultationStatus.cancelled : "skipped" in value ? ConsultationStatus.skipped : "completed" in value ? ConsultationStatus.completed : "called" in value ? ConsultationStatus.called : "waiting" in value ? ConsultationStatus.waiting : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoctorRequest>): Array<DoctorRequest> {
    return value.map((x)=>from_candid_DoctorRequest_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Doctor>): Array<Doctor> {
    return value.map((x)=>from_candid_Doctor_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, Array<_ConsultationToken>]>): Array<[bigint, Array<ConsultationToken>]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConsultationToken>): Array<ConsultationToken> {
    return value.map((x)=>from_candid_ConsultationToken_n8(_uploadFile, _downloadFile, x));
}
function to_candid_TokenResponse_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenResponse): _TokenResponse {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenResponse): {
    more_time: null;
} | {
    cancel: null;
} | {
    coming: null;
} {
    return value == TokenResponse.more_time ? {
        more_time: null
    } : value == TokenResponse.cancel ? {
        cancel: null
    } : value == TokenResponse.coming ? {
        coming: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
